DEFAULT_PORT = 7071
DEFAULT_FPS = 30
DEFAULT_NUMBER_OF_FRAME_TAKEN = 5

HTTP_STATUS_OK = 200
HTTP_STATUS_NO_CONTENT = 204
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_UNPROCESSABLE_ENTITY = 412

DEFAULT_PREFIX_BASE64 = 'data:image/jpeg;base64,'
DEFAULT_APP_NAME = 'stream-to-frame'
DEFAULT_DELAY_TIME_CONVERT_STREAM_TO_FRAME_SCHEDULER = 1
