INVALID_PAYLOAD_DATA_MESSAGE = 'Invalid Data'
INVALID_GATE_ID_MESSAGE = 'Invalid Gate ID'
OK_MESSAGE = 'OK'

MESSAGE_SUCCESS_SENT_DATA_TO_QUEUE = 'Data has successfully been sent to Queue'
MESSAGE_FAIL_SENT_DATA_TO_QUEUE = 'Failed to send data to Queue'
MESSAGE_UPLOAD_ERROR = 'an error has occurred when uploading to storage.'
MESSAGE_CANNOT_READ_STREAM = 'Cannot read data URL stream'
MESSAGE_DELETE_GATE_ID_SUCCESS = 'Gate ID has successfully been removed from database'
MESSAGE_DELETE_GATE_ID_FAILED = 'an error has occurred when removing Gate ID'
MESSAGE_GATE_ID_NOT_FOUND = 'Data Gate ID does not exists.'
MESSAGE_IMAGE_PAYLOAD_EMPTY = 'Payload Image is empty.'
MESSAGE_INVALID_TICKET_NUMBER = 'Invalid Ticket Number'
MESSAGE_WARNING_FILENAME_EMPTY = 'Filename must not be empty.'
MESSAGE_WARNING_ENCODED_FILE_EMPTY = 'Encoded File must not be empty.'
MESSAGE_WARNING_INVALID_FILE_EXTENSION = 'Invalid Extension File.'
MESSAGE_WARNING_URL_PAYLOAD_EMPTY = 'Url Payload is empty.'
