APP_NAME = "stream-to-frame-service"
LPR_STORAGE_APP_NAME = "lpr-storage-service"

DEFAULT_PORT = 7071
DEFAULT_PORT_EUREKA = 8761
DEFAULT_FPS = 30
DEFAULT_NUMBER_OF_FRAME_TAKEN = 5

HTTP_STATUS_OK = 200
HTTP_STATUS_NO_CONTENT = 204
HTTP_STATUS_BAD_REQUEST = 400
HTTP_STATUS_NOT_FOUND = 404
HTTP_STATUS_UNPROCESSABLE_ENTITY = 412

DEFAULT_PREFIX_BASE64 = 'data:image/jpeg;base64,'
DEFAULT_APP_NAME = 'stream-to-frame'
DEFAULT_DELAY_TIME_CONVERT_STREAM_TO_FRAME_SCHEDULER = 1
DEFAULT_JPG_IMAGE_QUALITY = 70  # scale 0-100

STATUS_PROCESSING = "PROCESSING"
STATUS_DONE = "DONE"
STATUS_RUNNING = "RUNNING"

DEFAULT_DATETIME_FORMAT = "YYYY-MM-DD HH:mm:ss"

IMAGE_EXT = ('.jpg', '.jpeg', '.png')

HTTP_REQUEST_METHOD_POST = "POST"
RETURN_TYPE_JSON = "Json"
