version: '3.0'
services:
  stream_to_frame:
    container_name: stream-to-frame
    image: python:3.8-slim
    command: poetry run python src/main.py -m http.server 7071
    ports:
      - 7071:7071
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - environment.env
    network_mode: "host"